### PR TITLE
Fix to ember-validations to accept 'content' property

### PR DESCRIPTION
**Pull request by gabesmed**
Hi Louis!

Thanks for writing this library! I've found it useful and incorporated it into my projects.

I made one small fix, where the current implementation doesn't like to nest errors inside any property that is also named 'content' -- this property conflicts with the ValidationError class's 'content' property. So I renamed the ValidationError's properties from 'content' and 'nestedErrors' to '_content' and '_nestedErrors'. And added a test.

Hope this helps!

-Gabe

### CODE REVIEW

**Comment by lcoq** [comment]
Nice! It seems to work. Could you rebase before merging please ?

**Comment by gabesmed** [comment]
Happy to -- but don't I need write access to your repository in order to rebase/merge? Sorry, I'm a bit inexperienced with rebasing.

**Comment by gabesmed** [comment]
hmm.. i don't think that worked as i'd hoped

**Comment by lcoq** [comment]
No problem, I fixed it. 
Merged in ac21b161b

Thank you!

**Pull request closed without merging**
